// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	listAllSessions: () => typedError<SessionMeta[], string>(__TAURI_INVOKE("list_all_sessions")),
	providerCaps: () => typedError<ProviderCapsEntry[], string>(__TAURI_INVOKE("provider_caps")),
	spawnSession: (providerId: string, spec: SpawnSpec) => typedError<SessionId, string>(__TAURI_INVOKE("spawn_session", { providerId, spec })),
	sendToSession: (id: SessionId, text: string) => typedError<null, string>(__TAURI_INVOKE("send_to_session", { id, text })),
	respondToPermission: (id: SessionId, requestId: string, response: PermissionResponse) => typedError<null, string>(__TAURI_INVOKE("respond_to_permission", { id, requestId, response })),
	/**
	 *  Answer an `AskUserQuestion`-style question or plan approval surfaced as a
	 *  `SessionEvent::Question` (G1, EKI-58).
	 */
	answerQuestion: (id: SessionId, response: QuestionResponse) => typedError<null, string>(__TAURI_INVOKE("answer_question", { id, response })),
	interruptSession: (id: SessionId) => typedError<null, string>(__TAURI_INVOKE("interrupt_session", { id })),
	killSession: (id: SessionId) => typedError<null, string>(__TAURI_INVOKE("kill_session", { id })),
	listPermissionRules: () => typedError<PermissionRule[], string>(__TAURI_INVOKE("list_permission_rules")),
	addPermissionRule: (rule: PermissionRule) => typedError<PermissionRule[], string>(__TAURI_INVOKE("add_permission_rule", { rule })),
	revokePermissionRule: (index: number) => typedError<PermissionRule[], string>(__TAURI_INVOKE("revoke_permission_rule", { index })),
	/**
	 *  One page of a session's transcript, numbered like live `Item.seq`
	 *  (D-M2-3): chat opens with the newest page and pages older on scroll-up.
	 */
	getSessionTranscript: (id: SessionId, offset: number, limit: number) => typedError<TranscriptPage, string>(__TAURI_INVOKE("get_session_transcript", { id, offset, limit })),
	listArchivedSessions: (projectPath: string | null) => typedError<ArchivedSession[], string>(__TAURI_INVOKE("list_archived_sessions", { projectPath })),
	searchTranscripts: (query: string) => typedError<SearchHit[], string>(__TAURI_INVOKE("search_transcripts", { query })),
	listAgents: () => typedError<Agent[], string>(__TAURI_INVOKE("list_agents")),
	createAgent: (input: NewAgent) => typedError<Agent, string>(__TAURI_INVOKE("create_agent", { input })),
	updateAgent: (agent: Agent) => typedError<Agent, string>(__TAURI_INVOKE("update_agent", { agent })),
	deleteAgent: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_agent", { id })),
	listProjects: () => typedError<Project[], string>(__TAURI_INVOKE("list_projects")),
	createProject: (input: NewProject) => typedError<Project, string>(__TAURI_INVOKE("create_project", { input })),
	updateProject: (project: Project) => typedError<Project, string>(__TAURI_INVOKE("update_project", { project })),
	deleteProject: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_project", { id })),
	listRooms: () => typedError<Room[], string>(__TAURI_INVOKE("list_rooms")),
	createRoom: (input: NewRoom) => typedError<Room, string>(__TAURI_INVOKE("create_room", { input })),
	updateRoom: (room: Room) => typedError<Room, string>(__TAURI_INVOKE("update_room", { room })),
	deleteRoom: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_room", { id })),
	listRoomRules: (roomId: string | null) => typedError<RoomRule[], string>(__TAURI_INVOKE("list_room_rules", { roomId })),
	createRoomRule: (input: NewRoomRule) => typedError<RoomRule, string>(__TAURI_INVOKE("create_room_rule", { input })),
	updateRoomRule: (rule: RoomRule) => typedError<RoomRule, string>(__TAURI_INVOKE("update_room_rule", { rule })),
	deleteRoomRule: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_room_rule", { id })),
	listTasks: () => typedError<Task[], string>(__TAURI_INVOKE("list_tasks")),
	/**
	 *  Single-task refetch for `TaskChanged` reconciliation (D-M3-2, G3):
	 *  `null` means the task was deleted — the store drops it.
	 */
	getTask: (id: string) => typedError<{
	id: string,
	project_id: string | null,
	room_id: string | null,
	title: string,
	description: string | null,
	status: string,
	priority: string,
	assignee_agent_id: string | null,
	created_by: string,
	created_at: number,
	updated_at: number,
} | null, string>(__TAURI_INVOKE("get_task", { id })),
	createTask: (input: NewTask) => typedError<Task, string>(__TAURI_INVOKE("create_task", { input })),
	updateTask: (task: Task) => typedError<Task, string>(__TAURI_INVOKE("update_task", { task })),
	deleteTask: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_task", { id })),
	/**
	 *  A task's timeline, oldest first: the drawer timeline, run linkage and
	 *  notification source all read from here.
	 */
	listTaskEvents: (taskId: string) => typedError<TaskEvent[], string>(__TAURI_INVOKE("list_task_events", { taskId })),
	/**
	 *  Run-with-agent linkage (T12 writes through here): records a `run_started`
	 *  timeline event. A card's linked session = newest `run_started` without a
	 *  matching `run_finished`.
	 */
	recordTaskRunStarted: (taskId: string, sessionId: SessionId, agentId: string | null) => typedError<TaskEvent, string>(__TAURI_INVOKE("record_task_run_started", { taskId, sessionId, agentId })),
	/**  The matching close of [`record_task_run_started`]. */
	recordTaskRunFinished: (taskId: string, sessionId: SessionId, outcome: string) => typedError<TaskEvent, string>(__TAURI_INVOKE("record_task_run_finished", { taskId, sessionId, outcome })),
	listSessionBindings: () => typedError<SessionBinding[], string>(__TAURI_INVOKE("list_session_bindings")),
	upsertSessionBinding: (input: NewSessionBinding) => typedError<SessionBinding, string>(__TAURI_INVOKE("upsert_session_binding", { input })),
	deleteSessionBinding: (sessionId: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_session_binding", { sessionId })),
	/**
	 *  Open the project in an external tool (EKI-80, D-M2-8): fixed argv mapped
	 *  from a closed enum, executed Rust-side — the webview gets no shell.
	 */
	handoff: (projectPath: string, target: HandoffTarget) => typedError<null, string>(__TAURI_INVOKE("handoff", { projectPath, target })),
	/**  Handoff targets installed on this machine. */
	handoffTargets: () => typedError<HandoffTarget[], string>(__TAURI_INVOKE("handoff_targets")),
	/**
	 *  Native folder picker (T3, D-M3-7): `tauri-plugin-dialog` invoked
	 *  RUST-SIDE only — the webview holds no `dialog:*` permission. Returns the
	 *  canonicalized folder, or `null` when the user cancels.
	 */
	pickFolder: () => typedError<string | null, string>(__TAURI_INVOKE("pick_folder")),
	listDocTree: (projectId: string) => typedError<DocEntry[], string>(__TAURI_INVOKE("list_doc_tree", { projectId })),
	readDocFile: (projectId: string, relPath: string) => typedError<string, string>(__TAURI_INVOKE("read_doc_file", { projectId, relPath })),
	readDocImage: (projectId: string, relPath: string) => typedError<DocImage, string>(__TAURI_INVOKE("read_doc_image", { projectId, relPath })),
	gitStatus: (projectPath: string) => typedError<GitStatus, string>(__TAURI_INVOKE("git_status", { projectPath })),
	gitDiff: (projectPath: string, base: string | null) => typedError<GitDiff, string>(__TAURI_INVOKE("git_diff", { projectPath, base })),
	gitDefaultBase: (projectPath: string) => typedError<string | null, string>(__TAURI_INVOKE("git_default_base", { projectPath })),
	/**
	 *  Composer hints: slash commands/skills any provider recognizes for the
	 *  project (G8). Read-only, path-policy-checked.
	 */
	listSlashCommands: (projectPath: string) => typedError<SlashCommand[], string>(__TAURI_INVOKE("list_slash_commands", { projectPath })),
	/**
	 *  Write/update the fenced persona block in the project's context file
	 *  (G9, EKI-32). Idempotent; uninstall is byte-identical (provider tests).
	 */
	materializePersona: (projectId: string, content: string) => typedError<null, string>(__TAURI_INVOKE("materialize_persona", { projectId, content })),
	/**  Remove the fenced persona block, restoring user content byte-identical. */
	removeMaterializedPersona: (projectId: string) => typedError<null, string>(__TAURI_INVOKE("remove_materialized_persona", { projectId })),
	listNotificationRules: () => typedError<NotificationRule[], string>(__TAURI_INVOKE("list_notification_rules")),
	createNotificationRule: (input: NewNotificationRule) => typedError<NotificationRule, string>(__TAURI_INVOKE("create_notification_rule", { input })),
	updateNotificationRule: (rule: NotificationRule) => typedError<NotificationRule, string>(__TAURI_INVOKE("update_notification_rule", { rule })),
	deleteNotificationRule: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_notification_rule", { id })),
	/**
	 *  Seed the M6 default attention rules (D-M6-4) — called by the wizard's
	 *  notifications opt-in. Idempotent; returns only newly created rules.
	 */
	seedDefaultNotificationRules: () => typedError<NotificationRule[], string>(__TAURI_INVOKE("seed_default_notification_rules")),
	getSetting: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_setting", { key })),
	setSetting: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_setting", { key, value })),
	/**
	 *  Open (or focus) the dedicated settings window (EKI-20, plan T10). The
	 *  window has its own least-privilege capability file
	 *  (`capabilities/settings.json`, core:default only); the webview renders the
	 *  settings panel when launched with `?window=settings`. Cross-window state
	 *  stays consistent via `SettingChanged` events (plan Appendix B): both
	 *  windows write through the same IPC and reconcile on the event.
	 */
	openSettingsWindow: () => typedError<null, string>(__TAURI_INVOKE("open_settings_window")),
	/**
	 *  Open (or focus) a dedicated workspace window (world-primary shell): the
	 *  panels in their own window, while the main window keeps the ONE 3D world.
	 *  Mirrors `open_settings_window` — own least-privilege capability file
	 *  (`capabilities/workspace.json`, core:default only); the webview renders
	 *  WorkspaceShell only when launched with `?window=workspace` (no world, no
	 *  wizard). Cross-window state stays consistent the same way: both windows
	 *  write through the same IPC and reconcile on domain events.
	 */
	openWorkspaceWindow: () => typedError<null, string>(__TAURI_INVOKE("open_workspace_window")),
	mcpStatus: () => typedError<McpStatus, string>(__TAURI_INVOKE("mcp_status")),
	enableMcpForProject: (projectId: string) => typedError<null, string>(__TAURI_INVOKE("enable_mcp_for_project", { projectId })),
	disableMcpForProject: (projectId: string) => typedError<null, string>(__TAURI_INVOKE("disable_mcp_for_project", { projectId })),
	listMeetings: (projectId: string | null) => typedError<Meeting[], string>(__TAURI_INVOKE("list_meetings", { projectId })),
	/**  Single-meeting refetch for `MeetingChanged` reconciliation (D-M4-11). */
	getMeeting: (id: string) => typedError<{
	id: string,
	title: string,
	goal: string | null,
	state: string,
	room_id: string | null,
	project_id: string | null,
	config_json: string | null,
	output_md: string | null,
	output_path: string | null,
	current_round: number | null,
	current_turn: number | null,
	started_at: number | null,
	completed_at: number | null,
	cancelled_at: number | null,
	error_message: string | null,
} | null, string>(__TAURI_INVOKE("get_meeting", { id })),
	listMeetingTurns: (meetingId: string) => typedError<MeetingTurn[], string>(__TAURI_INVOKE("list_meeting_turns", { meetingId })),
	listActionItems: (meetingId: string) => typedError<ActionItem[], string>(__TAURI_INVOKE("list_action_items", { meetingId })),
	/**
	 *  Start a meeting: persists the row + config, then the orchestrator drives
	 *  it (gathering → rounds → synthesis) over dedicated managed sessions.
	 */
	startMeeting: (spec: StartMeetingSpec) => typedError<Meeting, string>(__TAURI_INVOKE("start_meeting", { spec })),
	/**
	 *  Cancel: terminal state persisted immediately; the in-flight turn (if any)
	 *  is interrupted by the driver.
	 */
	cancelMeeting: (id: string) => typedError<Meeting, string>(__TAURI_INVOKE("cancel_meeting", { id })),
	/**
	 *  Convert an action item to a board task (16.3): one click on the existing
	 *  M3 surface. `room_id` falls back to the meeting's room — without either,
	 *  this errors (the standing room_id lesson: tasks without a room don't show
	 *  on any board, so the UI must ask).
	 */
	convertActionItem: (itemId: string, roomId: string | null) => typedError<Task, string>(__TAURI_INVOKE("convert_action_item", { itemId, roomId })),
	/**
	 *  Manual standup trigger: creates the row and fans out one bounded haiku
	 *  gathering run per agent in the background; entries stream in via
	 *  `StandupChanged`.
	 */
	runStandup: (agentIds: string[] | null, title: string | null) => typedError<Standup, string>(__TAURI_INVOKE("run_standup", { agentIds, title })),
	listStandups: () => typedError<Standup[], string>(__TAURI_INVOKE("list_standups")),
	/**  Single-standup refetch for `StandupChanged` reconciliation. */
	getStandup: (id: string) => typedError<{
	id: string,
	title: string,
	created_by: string | null,
	created_at: number,
} | null, string>(__TAURI_INVOKE("get_standup", { id })),
	listStandupEntries: (standupId: string) => typedError<StandupEntry[], string>(__TAURI_INVOKE("list_standup_entries", { standupId })),
	listRuns: () => typedError<Run[], string>(__TAURI_INVOKE("list_runs")),
	/**  Single-run refetch for `RunChanged` reconciliation. */
	getRun: (id: string) => typedError<{
	id: string,
	kind: string,
	schedule_cron: string | null,
	spec_json: string,
	enabled: boolean,
	last_run_at: number | null,
} | null, string>(__TAURI_INVOKE("get_run", { id })),
	/**
	 *  Create a run. `spec_json` is validated at write time against the tagged
	 *  union (prompt | sequence | standup); the cron expression (if any) must parse.
	 */
	createRun: (input: NewRun) => typedError<Run, string>(__TAURI_INVOKE("create_run", { input })),
	updateRun: (run: Run) => typedError<Run, string>(__TAURI_INVOKE("update_run", { run })),
	deleteRun: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_run", { id })),
	setRunEnabled: (id: string, enabled: boolean) => typedError<Run, string>(__TAURI_INVOKE("set_run_enabled", { id, enabled })),
	/**  "Run now": the same dispatcher code path as a scheduled firing (D-M4-5). */
	runNow: (runId: string) => typedError<RunResult, string>(__TAURI_INVOKE("run_now", { runId })),
	listRunResults: (runId: string) => typedError<RunResult[], string>(__TAURI_INVOKE("list_run_results", { runId })),
	previewCron: (expr: string) => typedError<CronPreview, string>(__TAURI_INVOKE("preview_cron", { expr })),
	/**  Global templates plus, when given, the project's own (D-M4-8). */
	listPromptTemplates: (projectId: string | null) => typedError<PromptTemplate[], string>(__TAURI_INVOKE("list_prompt_templates", { projectId })),
	createPromptTemplate: (input: NewPromptTemplate) => typedError<PromptTemplate, string>(__TAURI_INVOKE("create_prompt_template", { input })),
	updatePromptTemplate: (template: PromptTemplate) => typedError<PromptTemplate, string>(__TAURI_INVOKE("update_prompt_template", { template })),
	deletePromptTemplate: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_prompt_template", { id })),
	hooksStatus: () => typedError<HooksStatus, string>(__TAURI_INVOKE("hooks_status")),
	previewHooksInstall: () => typedError<HooksPreview, string>(__TAURI_INVOKE("preview_hooks_install")),
	installHooks: () => typedError<HooksStatus, string>(__TAURI_INVOKE("install_hooks")),
	uninstallHooks: () => typedError<HooksStatus, string>(__TAURI_INVOKE("uninstall_hooks")),
	/**
	 *  Probe the machine for the wizard's detect step; a found CLI path is
	 *  persisted so the provider config picks it up on next launch.
	 */
	detectEnvironment: () => typedError<EnvReport, string>(__TAURI_INVOKE("detect_environment")),
	/**
	 *  Manual CLI path picker re-probe (D-M6-3): persists the path and returns
	 *  the probed version line when the binary answers.
	 */
	setCliPath: (path: string) => typedError<string | null, string>(__TAURI_INVOKE("set_cli_path", { path })),
	/**
	 *  Recent unique project paths from the watcher meta cache, ranked by last
	 *  activity; already-registered project paths filtered out. No new scanner.
	 */
	scanRecentProjects: () => typedError<RecentProject[], string>(__TAURI_INVOKE("scan_recent_projects")),
	/**
	 *  Materialize the sample crew (D-M6-9) and announce it with the existing
	 *  coarse DomainEvents.
	 */
	createSampleCrew: () => typedError<SampleCrewResult, string>(__TAURI_INVOKE("create_sample_crew")),
	previewV1Import: (dbPath: string | null) => typedError<ImportReport, string>(__TAURI_INVOKE("preview_v1_import", { dbPath })),
	runV1Import: (dbPath: string | null, options: ImportOptions) => typedError<ImportReport, string>(__TAURI_INVOKE("run_v1_import", { dbPath, options })),
	/**
	 *  Assemble the local report bundle (version, OS/arch, last error lines —
	 *  NO transcript/settings content) and reveal it next to the user. Returns
	 *  the file path. Nothing leaves the machine.
	 */
	buildErrorReport: () => typedError<string, string>(__TAURI_INVOKE("build_error_report")),
	checkForUpdate: () => typedError<{
	version: string,
	notes: string | null,
	date: string | null,
} | null, string>(__TAURI_INVOKE("check_for_update")),
	/**
	 *  Download + verify + install, persisting `updater.pending_notes` for the
	 *  What's-new dialog, then relaunch. Only returns on failure.
	 */
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
};

/** Events */
export const events = {
	domainEvent: makeEvent<DomainEvent>("domain-event"),
	engineEvent: makeEvent<EngineEvent>("engine-event"),
};

/* Types */
export type ActionItem = {
	id: string,
	meeting_id: string,
	text: string,
	assignee_agent_id: string | null,
	priority: string | null,
	status: string,
	task_id: string | null,
	sort_order: number,
	created_at: number,
};

export type Agent = {
	id: string,
	name: string,
	icon: string | null,
	color: string | null,
	avatar: string | null,
	default_model: string | null,
	project_path: string | null,
	permission_mode: string,
	system_prompt: string | null,
	persona_json: string | null,
	is_pinned: boolean,
	auto_spawn: boolean,
	bio: string | null,
	created_at: number,
	updated_at: number,
};

export type AppInfo = {
	version: string,
	data_dir: string,
};

export type ArchivedSession = {
	id: SessionId,
	project_path: string,
	summary: string,
	last_modified_ms: number,
};

/**  A raw v1 blueprint row for the frontend conversion leg (D-M6-8). */
export type BlueprintRow = {
	id: string,
	name: string,
	room_id: string | null,
	blueprint_json: string,
};

/**
 *  Cron preview for the schedule editor: next 3 occurrences + a human
 *  description, plus the honest copy the panel must show (D-M4-4).
 */
export type CronPreview = {
	next: number[],
	desc: string | null,
	/**  "Schedules run only while CrewHub is open." */
	note: string,
};

export type DiffFile = {
	path: string,
	/**  One-letter porcelain status: A/M/D/R/C/T/U, or "B" for binary. */
	status: string,
	additions: number,
	deletions: number,
	patch: string,
};

export type DocEntry = {
	/**  Path relative to the docs root, `/`-separated. */
	rel_path: string,
	name: string,
	is_dir: boolean,
};

export type DocImage = {
	media_type: string,
	base64: string,
};

/**
 *  The single typed event stream the webview subscribes to.
 *  Every store mutation emits exactly one variant.
 */
export type DomainEvent = { type: "AgentCreated"; data: {
	agent_id: string,
} } | { type: "AgentUpdated"; data: {
	agent_id: string,
} } | { type: "AgentDeleted"; data: {
	agent_id: string,
} } | { type: "ProjectChanged"; data: {
	project_id: string,
} } | { type: "RoomChanged"; data: {
	room_id: string,
} } | { type: "TaskChanged"; data: {
	task_id: string,
} } | { type: "SettingChanged"; data: {
	key: string,
} } | 
/**  A session binding was created, updated or deleted (G3, EKI-40). */
{ type: "SessionBindingChanged"; data: {
	session_id: string,
} } | 
/**  Meeting state/turn progress (M4 D-M4-11) — UI refetches the meeting + turns. */
{ type: "MeetingChanged"; data: {
	meeting_id: string,
} } | 
/**  A run was created/updated/fired or a result landed — UI refetches. */
{ type: "RunChanged"; data: {
	run_id: string,
} } | 
/**  A standup entry landed — UI refetches the standup + entries. */
{ type: "StandupChanged"; data: {
	standup_id: string,
} };

/**  Wrapper event carrying provider-neutral engine events to the webview. */
export type EngineEvent = SessionEvent;

/**  Appendix C `EnvReport`. */
export type EnvReport = {
	/**  Resolved CLI path (persisted to the cli-path setting when found). */
	cli_path: string | null,
	/**  First line of `--version`, when the probe answered in time. */
	cli_version: string | null,
	/**  The agent runtime's user dir exists (it has been used on this machine). */
	claude_dir: boolean,
	/**  Its transcripts dir exists (recent-project scan will have material). */
	claude_projects: boolean,
	/**  Path to a CrewHub v1 database, when present (the importer hook). */
	v1_db: string | null,
};

export type GitDiff = {
	files: DiffFile[],
	truncated: boolean,
};

export type GitStatus = {
	branch: string,
	ahead: number,
	behind: number,
	/**  Tracked entries with changes (staged, unstaged or unmerged). */
	dirty: number,
	untracked: number,
	worktrees: Worktree[],
};

export type HandoffTarget = "Terminal" | "Iterm" | "Warp" | "Vscode" | "RevealInFinder";

export type HookSignal = {
	/**  Provider-neutral event name: session-start | pre-tool | post-tool | stop | subagent-stop | notification */
	event: string,
	tool: string | null,
	path: string | null,
	payload_json: string | null,
	ts: number,
};

/**  Before/after settings text for the wizard's real preview diff. */
export type HooksPreview = {
	before: string,
	after: string,
};

/**  Wire status of the hooks bridge (Appendix C `HooksStatus`). */
export type HooksStatus = {
	/**  False on Windows: the bridge is UDS-based; the app runs watcher-only. */
	supported: boolean,
	installed: boolean,
	settings_path: string,
	/**  The bundled `crewhub-signal` binary was found on disk. */
	sidecar_ok: boolean,
};

export type ImportOptions = {
	/**
	 *  v1 project id → folder path, for v1 projects without `folder_path`
	 *  (NOT NULL in v2). Projects without an override are skipped (counted).
	 */
	folder_overrides?: { [key in string]: string },
};

export type ImportReport = {
	db_path: string,
	/**  True for previews: nothing was written. */
	dry_run: boolean,
	tables: TableReport[],
	/**  Row-level warnings (lossy folds, flagged conversions). */
	warnings: string[],
	/**  v1 tables present but deliberately not imported (master plan §4.4). */
	not_imported: string[],
	blueprints: BlueprintRow[],
	imported: ImportedIds,
};

/**
 *  Ids that landed in v2 — the IPC layer fans these out as the existing
 *  coarse DomainEvents after commit (no new event variants, Appendix C).
 */
export type ImportedIds = {
	projects: string[],
	rooms: string[],
	agents: string[],
	tasks: string[],
	bindings: string[],
	templates: string[],
};

/**
 *  What the UI may know about the MCP server. The bearer token is
 *  deliberately absent: it never crosses into the webview.
 */
export type McpStatus = {
	port: number,
	url: string,
};

export type Meeting = {
	id: string,
	title: string,
	goal: string | null,
	state: string,
	room_id: string | null,
	project_id: string | null,
	config_json: string | null,
	output_md: string | null,
	output_path: string | null,
	current_round: number | null,
	current_turn: number | null,
	started_at: number | null,
	completed_at: number | null,
	cancelled_at: number | null,
	error_message: string | null,
};

export type MeetingTurn = {
	id: string,
	meeting_id: string,
	round_num: number,
	turn_index: number,
	agent_id: string,
	session_id: string | null,
	/**  Item-sequence offset in the participant's transcript at turn start. */
	transcript_offset: number | null,
	started_at: number | null,
	/**  NULL + meeting moved past it = the turn was skipped (💤). */
	completed_at: number | null,
};

export type NewAgent = {
	name: string,
	icon: string | null,
	color: string | null,
	default_model: string | null,
	project_path: string | null,
	permission_mode: string | null,
	system_prompt: string | null,
};

export type NewNotificationRule = {
	scope: string,
	scope_id: string | null,
	trigger: string,
	config_json: string | null,
	enabled: boolean | null,
};

export type NewProject = {
	name: string,
	description: string | null,
	icon: string | null,
	color: string | null,
	folder_path: string,
	docs_path: string | null,
};

export type NewPromptTemplate = {
	name: string,
	template: string,
	variables_json: string | null,
	project_id: string | null,
};

export type NewRoom = {
	project_id: string | null,
	name: string,
	icon: string | null,
	color: string | null,
	is_hq: boolean | null,
};

export type NewRoomRule = {
	room_id: string,
	rule_type: string,
	rule_value: string,
	priority: number | null,
};

export type NewRun = {
	kind: string,
	schedule_cron: string | null,
	spec_json: string,
};

/**
 *  Upsert input: the full desired state for one session (no partial patch —
 *  the UI always knows the current binding it is editing).
 */
export type NewSessionBinding = {
	session_id: string,
	agent_id: string | null,
	room_id: string | null,
	display_name: string | null,
	pinned: boolean,
};

export type NewTask = {
	project_id: string | null,
	room_id: string | null,
	title: string,
	description: string | null,
	priority: string | null,
	assignee_agent_id: string | null,
	created_by: string | null,
};

export type NotificationRule = {
	id: string,
	/**  agent | project | global */
	scope: string,
	/**  The agent/project id when scope is not global. */
	scope_id: string | null,
	/**  task_moved | task_blocked | task_assigned | task_mention */
	trigger: string,
	config_json: string | null,
	enabled: boolean,
};

export type ParticipantSpec = {
	agent_id: string,
	name: string,
	/**  Persona carried via the session's appended system prompt. */
	persona: string | null,
};

export type PermissionMode = "Default" | "AcceptEdits" | "Plan" | "BypassPermissions";

export type PermissionRequest = {
	request_id: string,
	tool: string,
	input_json: string,
	suggestions: string[],
};

export type PermissionResponse = { kind: "AllowOnce" } | { kind: "AllowAlways" } | { kind: "Deny"; data: {
	message: string | null,
} };

export type PermissionRule = {
	/**  None = applies to every agent. */
	agent_id: string | null,
	/**  Tool pattern: exact name, or prefix ending in `*` (e.g. `mcp__crewhub__*`). */
	tool_pattern: string,
};

export type Project = {
	id: string,
	name: string,
	description: string | null,
	icon: string | null,
	color: string | null,
	folder_path: string,
	docs_path: string | null,
	status: string,
	created_at: number,
	updated_at: number,
};

export type PromptTemplate = {
	id: string,
	name: string,
	template: string,
	variables_json: string | null,
	project_id: string | null,
};

export type ProviderCaps = {
	spawn: boolean,
	resume: boolean,
	fork: boolean,
	permissions: boolean,
	interrupt: boolean,
	thinking: boolean,
	subagents: boolean,
	headless_runs: boolean,
	hooks: boolean,
	mcp_registration: boolean,
};

/**
 *  `(provider id, caps)` pair — specta has no tuple-in-Vec ergonomics we want
 *  to expose, so this tiny named struct is the wire shape instead.
 */
export type ProviderCapsEntry = {
	provider: string,
	caps: ProviderCaps,
};

export type QuestionRequest = {
	request_id: string,
	/**  "question" | "plan" */
	kind: string,
	text: string,
	options: string[],
	multi_select: boolean,
};

export type QuestionResponse = {
	request_id: string,
	answers: string[],
};

/**  One ranked entry from the recent-project scan (Appendix C). */
export type RecentProject = {
	path: string,
	last_active_ms: number,
};

export type Room = {
	id: string,
	project_id: string | null,
	name: string,
	icon: string | null,
	color: string | null,
	sort_order: number,
	is_hq: boolean,
	style_json: string | null,
	created_at: number,
	updated_at: number,
};

export type RoomRule = {
	id: string,
	room_id: string,
	/**  keyword | model | path_pattern | origin */
	rule_type: string,
	rule_value: string,
	priority: number,
};

export type Run = {
	id: string,
	kind: string,
	schedule_cron: string | null,
	spec_json: string,
	enabled: boolean,
	last_run_at: number | null,
};

export type RunResult = {
	id: string,
	run_id: string,
	session_id: string | null,
	status: string,
	summary: string | null,
	/**  Position within a sequence (migration 003); NULL for simple runs. */
	step_index: number | null,
	started_at: number | null,
	finished_at: number | null,
};

export type SampleCrewResult = {
	project_id: string,
	room_ids: string[],
	agent_ids: string[],
	task_ids: string[],
};

export type SearchHit = {
	session_id: SessionId,
	ts: number,
	role: string,
	snippet: string,
};

/**
 *  A transcript item paired with its absolute position in the session's
 *  transcript — the SAME numbering as live [`SessionEvent::Item`] `seq`
 *  (M2 plan D-M2-3: one parser, one numbering).
 */
export type SeqItem = {
	seq: number,
	item: TranscriptItem,
};

export type SessionBinding = {
	session_id: string,
	agent_id: string | null,
	room_id: string | null,
	display_name: string | null,
	pinned: boolean,
	updated_at: number,
};

export type SessionEvent = { type: "Discovered"; data: {
	meta: SessionMeta,
} } | { type: "Updated"; data: {
	meta: SessionMeta,
} } | { type: "Removed"; data: {
	id: SessionId,
} } | { type: "Item"; data: {
	id: SessionId,
	item: TranscriptItem,
	seq: number,
} } | { type: "PermissionRequest"; data: {
	id: SessionId,
	request: PermissionRequest,
} } | { type: "Question"; data: {
	id: SessionId,
	question: QuestionRequest,
} } | { type: "Signal"; data: {
	id: SessionId,
	signal: HookSignal,
} } | { type: "Conflict"; data: {
	path: string,
	sessions: SessionId[],
} };

export type SessionId = {
	provider: string,
	id: string,
};

export type SessionMeta = {
	id: SessionId,
	origin: SessionOrigin,
	project_path: string,
	model: string | null,
	status: SessionStatus,
	activity_detail: string | null,
	parent: SessionId | null,
	/**  Present only when the provider detected team membership (D-M4-9). */
	team: TeamInfo | null,
	usage: UsageTotals,
	git_branch: string | null,
	last_activity_ms: number,
};

export type SessionOrigin = "Managed" | "External";

export type SessionStatus = "Working" | "WaitingForInput" | "WaitingForPermission" | "Idle" | "Ended";

export type SkipCount = {
	reason: string,
	count: number,
};

/**
 *  A composer hint: a slash command or skill the provider recognizes for a
 *  given project (G8, EKI-52).
 */
export type SlashCommand = {
	name: string,
	description: string | null,
};

export type SpawnSpec = {
	project_path: string,
	prompt: string | null,
	model: string | null,
	permission_mode: PermissionMode,
	/**  Resume this session id; with `fork: true` the original stays untouched. */
	resume_session: string | null,
	fork: boolean,
	append_system_prompt: string | null,
	agent_id: string | null,
};

export type Standup = {
	id: string,
	title: string,
	created_by: string | null,
	created_at: number,
};

export type StandupEntry = {
	id: string,
	standup_id: string,
	agent_id: string,
	yesterday: string | null,
	today: string | null,
	blockers: string | null,
	submitted_at: number,
};

/**
 *  IPC-facing spec for `start_meeting` (models default from the policy keys;
 *  the dialog pre-fills and may override per meeting — D-M4-3).
 */
export type StartMeetingSpec = {
	title: string,
	goal: string | null,
	room_id: string | null,
	project_id: string | null,
	project_path: string,
	participants: ParticipantSpec[],
	rounds: number | null,
	turn_timeout_ms: number | null,
	participant_model: string | null,
	synthesis_model: string | null,
	context_docs: string[] | null,
};

export type TableReport = {
	table: string,
	found: number,
	will_import: number,
	/**  Row skips AND named field-level drops, both counted (never silent). */
	skipped: SkipCount[],
};

export type Task = {
	id: string,
	project_id: string | null,
	room_id: string | null,
	title: string,
	description: string | null,
	status: string,
	priority: string,
	assignee_agent_id: string | null,
	created_by: string,
	created_at: number,
	updated_at: number,
};

export type TaskEvent = {
	id: string,
	task_id: string,
	event_type: string,
	actor: string,
	payload_json: string | null,
	created_at: number,
};

/**
 *  Team membership (M4 D-M4-9, 18.1): provider-neutral and ADDITIVE — the UI
 *  tolerates `None` by construction; detection is parse-tolerant (unknown
 *  shapes = no team, never an error).
 */
export type TeamInfo = {
	/**  Team name when resolvable; otherwise a stable group key. */
	team_id: string,
	/**  "lead" or the teammate's name. */
	role: string,
};

/**
 *  Provider-neutral transcript item. Provider-specific raw lines are MAPPED into this,
 *  never exposed. `Unknown` preserves the raw type so the UI can render an
 *  "unsupported item" placeholder and we never crash on format drift.
 */
export type TranscriptItem = { kind: "UserText"; data: {
	text: string,
	ts: number,
} } | { kind: "AssistantText"; data: {
	text: string,
	ts: number,
} } | { kind: "Thinking"; data: {
	text: string | null,
	redacted: boolean,
	ts: number,
} } | { kind: "ToolUse"; data: {
	tool: string,
	input_json: string,
	tool_use_id: string,
	ts: number,
} } | { kind: "ToolResult"; data: {
	tool_use_id: string,
	output_preview: string,
	is_error: boolean,
	ts: number,
} } | { kind: "Image"; data: {
	media_type: string,
	ts: number,
} } | { kind: "SystemNote"; data: {
	text: string,
	ts: number,
} } | { kind: "Usage"; data: {
	input_tokens: number,
	output_tokens: number,
	cache_read: number,
	ts: number,
} } | 
/**
 *  A provider-made restore point (e.g. a file-history snapshot) the user
 *  can rewind to by forking from here (EKI-64).
 */
{ kind: "Checkpoint"; data: {
	id: string,
	ts: number,
} } | { kind: "Unknown"; data: {
	raw_type: string,
	ts: number,
} };

/**  One page of an on-disk transcript: items `[offset, offset+limit)`. */
export type TranscriptPage = {
	items: SeqItem[],
	/**  Items currently in the transcript file. */
	total: number,
};

export type UpdateInfo = {
	version: string,
	notes: string | null,
	date: string | null,
};

export type UsageTotals = {
	input_tokens: number,
	output_tokens: number,
	cache_read_tokens: number,
};

export type Worktree = {
	path: string,
	branch: string | null,
	is_current: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

