// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	listAllSessions: () => typedError<SessionMeta[], string>(__TAURI_INVOKE("list_all_sessions")),
	listAgents: () => typedError<Agent[], string>(__TAURI_INVOKE("list_agents")),
	createAgent: (input: NewAgent) => typedError<Agent, string>(__TAURI_INVOKE("create_agent", { input })),
	updateAgent: (agent: Agent) => typedError<Agent, string>(__TAURI_INVOKE("update_agent", { agent })),
	deleteAgent: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_agent", { id })),
	listProjects: () => typedError<Project[], string>(__TAURI_INVOKE("list_projects")),
	createProject: (input: NewProject) => typedError<Project, string>(__TAURI_INVOKE("create_project", { input })),
	updateProject: (project: Project) => typedError<Project, string>(__TAURI_INVOKE("update_project", { project })),
	deleteProject: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_project", { id })),
	listRooms: () => typedError<Room[], string>(__TAURI_INVOKE("list_rooms")),
	createRoom: (input: NewRoom) => typedError<Room, string>(__TAURI_INVOKE("create_room", { input })),
	updateRoom: (room: Room) => typedError<Room, string>(__TAURI_INVOKE("update_room", { room })),
	deleteRoom: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_room", { id })),
	listTasks: () => typedError<Task[], string>(__TAURI_INVOKE("list_tasks")),
	createTask: (input: NewTask) => typedError<Task, string>(__TAURI_INVOKE("create_task", { input })),
	updateTask: (task: Task) => typedError<Task, string>(__TAURI_INVOKE("update_task", { task })),
	deleteTask: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_task", { id })),
	getSetting: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_setting", { key })),
	setSetting: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_setting", { key, value })),
};

/** Events */
export const events = {
	domainEvent: makeEvent<DomainEvent>("domain-event"),
	engineEvent: makeEvent<EngineEvent>("engine-event"),
};

/* Types */
export type Agent = {
	id: string,
	name: string,
	icon: string | null,
	color: string | null,
	avatar: string | null,
	default_model: string | null,
	project_path: string | null,
	permission_mode: string,
	system_prompt: string | null,
	persona_json: string | null,
	is_pinned: boolean,
	auto_spawn: boolean,
	bio: string | null,
	created_at: number,
	updated_at: number,
};

export type AppInfo = {
	version: string,
	data_dir: string,
};

/**
 *  The single typed event stream the webview subscribes to.
 *  Every store mutation emits exactly one variant.
 */
export type DomainEvent = { type: "AgentCreated"; data: {
	agent_id: string,
} } | { type: "AgentUpdated"; data: {
	agent_id: string,
} } | { type: "AgentDeleted"; data: {
	agent_id: string,
} } | { type: "ProjectChanged"; data: {
	project_id: string,
} } | { type: "RoomChanged"; data: {
	room_id: string,
} } | { type: "TaskChanged"; data: {
	task_id: string,
} } | { type: "SettingChanged"; data: {
	key: string,
} };

/**  Wrapper event carrying provider-neutral engine events to the webview. */
export type EngineEvent = SessionEvent;

export type HookSignal = {
	/**  Provider-neutral event name: session-start | pre-tool | post-tool | stop | subagent-stop | notification */
	event: string,
	tool: string | null,
	path: string | null,
	payload_json: string | null,
	ts: number,
};

export type NewAgent = {
	name: string,
	icon: string | null,
	color: string | null,
	default_model: string | null,
	project_path: string | null,
	permission_mode: string | null,
	system_prompt: string | null,
};

export type NewProject = {
	name: string,
	description: string | null,
	icon: string | null,
	color: string | null,
	folder_path: string,
	docs_path: string | null,
};

export type NewRoom = {
	project_id: string | null,
	name: string,
	icon: string | null,
	color: string | null,
	is_hq: boolean | null,
};

export type NewTask = {
	project_id: string | null,
	room_id: string | null,
	title: string,
	description: string | null,
	priority: string | null,
	assignee_agent_id: string | null,
	created_by: string | null,
};

export type PermissionRequest = {
	request_id: string,
	tool: string,
	input_json: string,
	suggestions: string[],
};

export type Project = {
	id: string,
	name: string,
	description: string | null,
	icon: string | null,
	color: string | null,
	folder_path: string,
	docs_path: string | null,
	status: string,
	created_at: number,
	updated_at: number,
};

export type QuestionRequest = {
	request_id: string,
	/**  "question" | "plan" */
	kind: string,
	text: string,
	options: string[],
	multi_select: boolean,
};

export type Room = {
	id: string,
	project_id: string | null,
	name: string,
	icon: string | null,
	color: string | null,
	sort_order: number,
	is_hq: boolean,
	style_json: string | null,
	created_at: number,
	updated_at: number,
};

export type SessionEvent = { type: "Discovered"; data: {
	meta: SessionMeta,
} } | { type: "Updated"; data: {
	meta: SessionMeta,
} } | { type: "Removed"; data: {
	id: SessionId,
} } | { type: "Item"; data: {
	id: SessionId,
	item: TranscriptItem,
	seq: number,
} } | { type: "PermissionRequest"; data: {
	id: SessionId,
	request: PermissionRequest,
} } | { type: "Question"; data: {
	id: SessionId,
	question: QuestionRequest,
} } | { type: "Signal"; data: {
	id: SessionId,
	signal: HookSignal,
} } | { type: "Conflict"; data: {
	path: string,
	sessions: SessionId[],
} };

export type SessionId = {
	provider: string,
	id: string,
};

export type SessionMeta = {
	id: SessionId,
	origin: SessionOrigin,
	project_path: string,
	model: string | null,
	status: SessionStatus,
	activity_detail: string | null,
	parent: SessionId | null,
	usage: UsageTotals,
	git_branch: string | null,
	last_activity_ms: number,
};

export type SessionOrigin = "Managed" | "External";

export type SessionStatus = "Working" | "WaitingForInput" | "WaitingForPermission" | "Idle" | "Ended";

export type Task = {
	id: string,
	project_id: string | null,
	room_id: string | null,
	title: string,
	description: string | null,
	status: string,
	priority: string,
	assignee_agent_id: string | null,
	created_by: string,
	created_at: number,
	updated_at: number,
};

/**
 *  Provider-neutral transcript item. Provider-specific raw lines are MAPPED into this,
 *  never exposed. `Unknown` preserves the raw type so the UI can render an
 *  "unsupported item" placeholder and we never crash on format drift.
 */
export type TranscriptItem = { kind: "UserText"; data: {
	text: string,
	ts: number,
} } | { kind: "AssistantText"; data: {
	text: string,
	ts: number,
} } | { kind: "Thinking"; data: {
	text: string | null,
	redacted: boolean,
	ts: number,
} } | { kind: "ToolUse"; data: {
	tool: string,
	input_json: string,
	tool_use_id: string,
	ts: number,
} } | { kind: "ToolResult"; data: {
	tool_use_id: string,
	output_preview: string,
	is_error: boolean,
	ts: number,
} } | { kind: "Image"; data: {
	media_type: string,
	ts: number,
} } | { kind: "SystemNote"; data: {
	text: string,
	ts: number,
} } | { kind: "Usage"; data: {
	input_tokens: number,
	output_tokens: number,
	cache_read: number,
	ts: number,
} } | { kind: "Unknown"; data: {
	raw_type: string,
	ts: number,
} };

export type UsageTotals = {
	input_tokens: number,
	output_tokens: number,
	cache_read_tokens: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

